"""initial schema

Revision ID: 69a8f4f217c7
Revises: 3bce51306165
Create Date: 2026-04-14 06:02:14.316148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a8f4f217c7'
down_revision: Union[str, Sequence[str], None] = '3bce51306165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_refs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'blocked', 'done', name='taskstatus'), nullable=True),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('source_ref_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_ref_id'], ['source_refs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connector_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connector_name', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_task_id', sa.String(), nullable=True),
    sa.Column('to_task_id', sa.String(), nullable=True),
    sa.Column('dep_type', sa.Enum('blocks', 'informs', 'requires_approval', name='dependencytype'), nullable=True),
    sa.ForeignKeyConstraint(['from_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['to_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependencies')
    op.drop_table('connector_runs')
    op.drop_table('tasks')
    op.drop_table('source_refs')
    op.drop_table('teams')
    # ### end Alembic commands ###
